"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-07-17 13:00:06.065675

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import sag_api.db.base

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('avatar', sa.String(length=64), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('persona_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_is_default'), ['is_default'], unique=False)

    op.create_table('settings',
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('scope', 'key', name='uq_setting_scope_key')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_scope'), ['scope'], unique=False)

    op.create_table('sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('DOCUMENT', 'WEB', 'MESSAGE', 'AUDIO', name='sourcetype', native_enum=False, length=16), nullable=False),
    sa.Column('connector_kind', sa.Enum('FILE_UPLOAD', 'WEB', name='connectorkind', native_enum=False, length=32), nullable=False),
    sa.Column('sag_source_config_id', sa.String(length=64), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ERROR', name='sourcestatus', native_enum=False, length=16), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_sag_source_config_id'), ['sag_source_config_id'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('agent_bindings',
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.Enum('SOURCE', 'MCP_SERVER', name='bindingtargettype', native_enum=False, length=16), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_bindings_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_bindings')),
    sa.UniqueConstraint('agent_id', 'target_type', 'target_id', name='uq_agent_binding')
    )
    with op.batch_alter_table('agent_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_bindings_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_bindings_target_id'), ['target_id'], unique=False)

    op.create_table('documents',
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'LOADING', 'EXTRACTING', 'PAUSED', 'READY', 'FAILED', name='documentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('token_usage', sa.BigInteger(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sag_source_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_documents_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_documents_source_sag_source', ['source_id', 'sag_source_id'], unique=False)

    op.create_table('exploration_sessions',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_ids_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exploration_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exploration_sessions'))
    )
    with op.batch_alter_table('exploration_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exploration_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_exploration_user_updated', ['user_id', 'updated_at'], unique=False)

    op.create_table('threads',
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_threads_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads'))
    )
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threads_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_archived'), ['archived'], unique=False)

    op.create_table('universe_dirty_sources',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_universe_dirty_sources_source_id_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_universe_dirty_sources_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universe_dirty_sources')),
    sa.UniqueConstraint('user_id', 'source_id', name='uq_universe_dirty_user_source')
    )
    with op.batch_alter_table('universe_dirty_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universe_dirty_sources_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_universe_dirty_sources_user_id'), ['user_id'], unique=False)

    op.create_table('universe_overviews',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('partition_count', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('relation_count', sa.Integer(), nullable=False),
    sa.Column('bounds_json', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('as_of', sag_api.db.base.UTCDateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('completed_at', sag_api.db.base.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_universe_overviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universe_overviews'))
    )
    with op.batch_alter_table('universe_overviews', schema=None) as batch_op:
        batch_op.create_index('ix_universe_overview_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index('ix_universe_overview_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_universe_overviews_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_universe_overviews_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_universe_overviews_user_id'), ['user_id'], unique=False)

    op.create_table('exploration_steps',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_ids_json', sa.JSON(), nullable=False),
    sa.Column('event_refs_json', sa.JSON(), nullable=False),
    sa.Column('entity_refs_json', sa.JSON(), nullable=False),
    sa.Column('relation_refs_json', sa.JSON(), nullable=False),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('camera_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exploration_sessions.id'], name=op.f('fk_exploration_steps_session_id_exploration_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exploration_steps'))
    )
    with op.batch_alter_table('exploration_steps', schema=None) as batch_op:
        batch_op.create_index('ix_exploration_step_session_created', ['session_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exploration_steps_session_id'), ['session_id'], unique=False)

    op.create_table('jobs',
    sa.Column('type', sa.Enum('PROCESS_DOCUMENT', 'SYNC_SOURCE', 'INDEX_UNIVERSE', name='jobtype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'PAUSED', 'SUCCEEDED', 'FAILED', name='jobstatus', native_enum=False, length=16), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sag_api.db.base.UTCDateTime(), nullable=True),
    sa.Column('finished_at', sag_api.db.base.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_jobs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('messages',
    sa.Column('thread_id', sa.String(length=32), nullable=False),
    sa.Column('attachments_json', sa.JSON(), nullable=False),
    sa.Column('steps_json', sa.JSON(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations_json', sa.JSON(), nullable=False),
    sa.Column('prompt_preview', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name=op.f('fk_messages_thread_id_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_thread_created_id', ['thread_id', 'created_at', 'id'], unique=False)

    op.create_table('universe_partitions',
    sa.Column('overview_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('relation_count', sa.Integer(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('time_range_json', sa.JSON(), nullable=False),
    sa.Column('time_buckets_json', sa.JSON(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sag_api.db.base.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['overview_id'], ['universe_overviews.id'], name=op.f('fk_universe_partitions_overview_id_universe_overviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['universe_partitions.id'], name=op.f('fk_universe_partitions_parent_id_universe_partitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_universe_partitions_source_id_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_universe_partitions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universe_partitions')),
    sa.UniqueConstraint('overview_id', 'source_id', 'kind', 'key', name='uq_universe_partition_key')
    )
    with op.batch_alter_table('universe_partitions', schema=None) as batch_op:
        batch_op.create_index('ix_universe_partition_overview_kind', ['overview_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_universe_partitions_overview_id'), ['overview_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_universe_partitions_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_universe_partitions_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_universe_partitions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universe_partitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universe_partitions_user_id'))
        batch_op.drop_index(batch_op.f('ix_universe_partitions_source_id'))
        batch_op.drop_index(batch_op.f('ix_universe_partitions_parent_id'))
        batch_op.drop_index(batch_op.f('ix_universe_partitions_overview_id'))
        batch_op.drop_index('ix_universe_partition_overview_kind')

    op.drop_table('universe_partitions')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_thread_created_id')

    op.drop_table('messages')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_source_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_document_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('exploration_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exploration_steps_session_id'))
        batch_op.drop_index('ix_exploration_step_session_created')

    op.drop_table('exploration_steps')
    with op.batch_alter_table('universe_overviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universe_overviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_universe_overviews_status'))
        batch_op.drop_index(batch_op.f('ix_universe_overviews_is_active'))
        batch_op.drop_index('ix_universe_overview_user_status')
        batch_op.drop_index('ix_universe_overview_user_active')

    op.drop_table('universe_overviews')
    with op.batch_alter_table('universe_dirty_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universe_dirty_sources_user_id'))
        batch_op.drop_index(batch_op.f('ix_universe_dirty_sources_source_id'))

    op.drop_table('universe_dirty_sources')
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threads_archived'))
        batch_op.drop_index(batch_op.f('ix_threads_agent_id'))

    op.drop_table('threads')
    with op.batch_alter_table('exploration_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_exploration_user_updated')
        batch_op.drop_index(batch_op.f('ix_exploration_sessions_user_id'))

    op.drop_table('exploration_sessions')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_source_sag_source')
        batch_op.drop_index(batch_op.f('ix_documents_source_id'))

    op.drop_table('documents')
    with op.batch_alter_table('agent_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_bindings_target_id'))
        batch_op.drop_index(batch_op.f('ix_agent_bindings_agent_id'))

    op.drop_table('agent_bindings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_sag_source_config_id'))

    op.drop_table('sources')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_scope'))
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_is_default'))

    op.drop_table('agents')
    # ### end Alembic commands ###
